version: "3.8"

## The Ports should only be exposed to other containers in the same network not the host

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb:iassil
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - meine_net
    healthcheck:
      test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 10

  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx:iassil
    container_name: my_nginx
    hostname: my_nginx
    restart: always
    depends_on:
    - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_db:/var/www/wordpress/
    networks:
      - meine_net
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 5s

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    image: wordpress:iassil
    container_name: my_wordpress
    hostname: my_wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_db:/var/www/wordpress/
    networks:
      - meine_net
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  db_data:
    name: "database_vol"
    driver: local
    driver_opts:
      device: "/home/${USER}/data/mariadb"
      o: bind
      type: none

  wordpress_db:
    name: "wordpress_database"
    driver: local
    driver_opts:
      device: "/home/${USER}/data/wordpress_db"
      o: bind
      type: none

networks:
  meine_net:
    name: "meine_net"
    driver: bridge
