version: "3.8"

## The Ports should only be exposed to other containers in the same network not the host

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb:iassil
    container_name: my_mariadb
    restart: always
    expose:
      - "3306"
    # ports:
    #   - "3306:3306"
    #   - target: 3306
    #     published: 3306
    #     protocol: tcp
    #     mode: host
    #   - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - meine_net

  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx:iassil
    container_name: my_nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    # expose:
    #   - "9000"
    # ports:
    #   - target: 80
    #     published: 8000
    #     protocol: tcp
    #     mode: host
    #   - "8000:80"
    env_file:
      - .env
    volumes:
      - wordpress_db:/etc/nginx/ssl/
    networks:
      - meine_net

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    image: wordpress:iassil
    container_name: my_wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_db:/var/www/html
    networks:
      - meine_net
    depends_on:
      - mariadb

volumes:
  db_data:
    name: "database_vol"
    driver: local
    driver_opts:
      device: "/home/${USER}/data/mariadb"
      o: bind
      type: none

  wordpress_db:
    name: "wordpress_database"
    driver: local
    driver_opts:
      device: "/home/${USER}/data/wordpress_db"
      o: bind
      type: none

networks:
  meine_net:
    name: "meine_net"
    driver: bridge
    # external: true
