version: "3.8"

services:
  mariadb:
    build:
      dockerfile: Dockerfile
      context: ./requirements/mariadb/
    container_name: my_mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - meine_net

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./requirements/nginx/
    container_name: my_nginx
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - wordpress_db:
    networks:
      - meine_net

  wordpress:
    build:
      dockerfile: Dockerfile
      context: ./requirements/wordpress/
    container_name: my_wordpress
    restart: always
    volumes:
      - wordpress_db:/var/www/html
    networks:
      - meine_net
    depends_on:
      - nginx
  

volumes:
  db_data:
  wordpress_db:

networks:
  meine_net:
    driver: bridge